metadata:
  ngsReports:
    kitManufacturer: ${KIT_MANUFACTURER:Archer}
    sequencer: ${SEQUENCER:Illumina NovaSeq 6000}
    referenceGenome: ${REFERENCE_GENOME:GRCh37}
    sequencingType: ${SEQUENCING_TYPE:PanelKit}
    sequencingTypeShort: ${SEQUENCING_TYPE_SHORT:Panel}
    interpolationSystem: ${INTERPOLATION_SYSTEM:MH Guide}
    reportedFocality: ${REPORTED_FOCALITY:complete}
    panelVP: ${PANEL_VP:VP-CST}
    panelVPCP: ${PANEL_VP_CP:VP-CST+FP-PST}
    seqKitTypVP: ${SEQKITTYP_VP:VP-CST}
    seqPipelineVP: ${SEQPIPELINE_VP:urn:Marburg:VP:CST:1.0:MHGuide:6.3.0}
    seqKitTypVPCP: ${SEQKITTYP_VPCP:VP-CST+FP-PST}
    seqPipelineVPCP: ${SEQPIPELINE_VPCP:urn:Marburg:VP:CST:1.0:FP:PST:1.0:MHGuide:6.3.0}
    fachabteilungKennung: ${FACHABTEILUNGKENNUNG:ITCCC}
    einrichtungKennung: ${EINRICHTUNGKENNUNG:CCCUMR}
    durchfuehrendeOE: ${DURCHFUEHRENDEOE:CCCUMR}
    durchfuehrendeOEKurzText: ${DURCHFUEHRENDEOE_KURZTEXT:CCC Marburg}
    internExternWert: ${INTERNEXTERN_WERT:M}
    internExternKurztext: ${INTERNEXTERN_KURZTEXT:Meine Einrichtung}
    analyseMethoden: ${ANALYSE_METHODE:S,KOMPBIO}
    classificationName: ${CLASSIFICATION_NAME:Likely pathogenic,Pathogenic}
    oncogenicClassificationName: ${ONCOGENIC_CLASSIFICATION_NAME:Likely oncogenic,Oncogenic}
